/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ModeloCarga.PremiosComboBox;

/**
 *
 * @author 8a
 */
public class Cargo extends javax.swing.JFrame {

    /**
     * Creates new form Cargo
     */
    public Cargo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_cargo = new javax.swing.JLabel();
        txtIdCargo = new javax.swing.JTextField();
        id_premio = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        cmbPremio = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNum_cue = new javax.swing.JTextField();
        JDate = new com.toedter.calendar.JDateChooser();
        num1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_cargo.setText("ID_CARGO");
        getContentPane().add(id_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));
        getContentPane().add(txtIdCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 80, -1));

        id_premio.setText("Premio:");
        getContentPane().add(id_premio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        num.setText("FECHA:");
        getContentPane().add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 20));

        getContentPane().add(cmbPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, -1));

        btnAceptar.setText("Aceptar");
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        txtNum_cue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum_cueActionPerformed(evt);
            }
        });
        getContentPane().add(txtNum_cue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, -1));
        getContentPane().add(JDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 20));

        num1.setText("Número de cuenta");
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNum_cueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum_cueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum_cueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser JDate;
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JComboBox<PremiosComboBox> cmbPremio;
    public javax.swing.JLabel id_cargo;
    public javax.swing.JLabel id_premio;
    public javax.swing.JLabel num;
    public javax.swing.JLabel num1;
    public javax.swing.JTextField txtIdCargo;
    public javax.swing.JTextField txtNum_cue;
    // End of variables declaration//GEN-END:variables
}
