/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author 8a
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbotones = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnPremios = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnAbono = new javax.swing.JButton();
        btnCargo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMovimientos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbotones.setBackground(new java.awt.Color(255, 255, 255));
        panelbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8-cliente-de-empresa-100.png"))); // NOI18N
        btnCliente.setBorder(null);
        btnCliente.setBorderPainted(false);
        btnCliente.setContentAreaFilled(false);
        panelbotones.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8-tarjeta-de-empleado-100.png"))); // NOI18N
        btnEmpleado.setBorder(null);
        btnEmpleado.setBorderPainted(false);
        btnEmpleado.setContentAreaFilled(false);
        panelbotones.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        btnPremios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8-trofeo-100 (2).png"))); // NOI18N
        btnPremios.setBorder(null);
        btnPremios.setBorderPainted(false);
        btnPremios.setContentAreaFilled(false);
        panelbotones.add(btnPremios, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8-carrito-de-compras-100.png"))); // NOI18N
        btnCompras.setBorder(null);
        btnCompras.setBorderPainted(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCompras.setDefaultCapable(false);
        btnCompras.setFocusPainted(false);
        btnCompras.setFocusable(false);
        panelbotones.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        btnAbono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8-verificar-100.png"))); // NOI18N
        btnAbono.setBorder(null);
        btnAbono.setBorderPainted(false);
        btnAbono.setContentAreaFilled(false);
        panelbotones.add(btnAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        btnCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8-monedero-100.png"))); // NOI18N
        btnCargo.setBorder(null);
        btnCargo.setBorderPainted(false);
        btnCargo.setContentAreaFilled(false);
        panelbotones.add(btnCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(22, 160, 133));
        jLabel2.setText("Premios");
        panelbotones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 160, 133));
        jLabel3.setText("Abono");
        panelbotones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, -1, 20));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 160, 133));
        jLabel4.setText("Clientes");
        panelbotones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 160, 133));
        jLabel5.setText("Empleados");
        panelbotones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        btnMovimientos.setBackground(new java.awt.Color(22, 155, 125));
        btnMovimientos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMovimientos.setForeground(new java.awt.Color(22, 155, 125));
        btnMovimientos.setText("Reportes/Movimientos");
        btnMovimientos.setBorder(null);
        btnMovimientos.setContentAreaFilled(false);
        btnMovimientos.setDefaultCapable(false);
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });
        panelbotones.add(btnMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(22, 160, 133));
        jLabel6.setText("Compras");
        panelbotones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 20));

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 160, 133));
        jLabel7.setText("Cargo");
        panelbotones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Menú principal");
        panelbotones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 155, 135));
        jLabel1.setText("Monedero Electrónico");
        panelbotones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        getContentPane().add(panelbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1018, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovimientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbono;
    public javax.swing.JButton btnCargo;
    public javax.swing.JButton btnCliente;
    public javax.swing.JButton btnCompras;
    public javax.swing.JButton btnEmpleado;
    public javax.swing.JButton btnMovimientos;
    public javax.swing.JButton btnPremios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel panelbotones;
    // End of variables declaration//GEN-END:variables
}
